### ISSUE TITLE
Evaluation globals

### ISSUE THREAD

**Issue by luvies** [luvies/node-business-rules#2]
for the evaluated expressions to be of use, we need some standard globals that can be accessed.

- [ ] Math
  - [ ] List all functions that will be available

**Comment by luvies** [comment]
The `Math` global will need to have most, if not all, of the standard JS math functions, but it will need some extra checks to ensure type correctness.

**Comment by timstableford** [comment]
Yeah, we likely also want to wrap Math.min() in a (list) => Math.min(...list) to map the array to an argument list since TS doesn't like it

**Comment by luvies** [comment]
This has been implemented for a while
