### ISSUE TITLE
Add support for rules to use the result of other rules

### ISSUE THREAD

**Issue by timstableford** [luvies/node-business-rules#8]

**Comment by timstableford** [comment]
I added a sort of dependency tree. Take a look and let me know how awful it is? :p

**Comment by luvies** [comment]
have a look at 1e01c4e, I've adjusted it so that we use `Map` and `Set` to store both rules and the dependency tree. I think the dependency tree is alright, but I'll be happier once I set up the testing framework.

**Comment by luvies** [comment]
I see you already set something up, but I was going to use Jest so I'll have a look

**Comment by luvies** [comment]
see c6040bc...94c0190

**Comment by timstableford** [comment]
Ehhh, I think it's less readable for the sake of optimisation without a purpose. But it works so it doesn't really matter :)

**Comment by luvies** [comment]
\>:( it took me too long to figure out what the filters were actually doing, and using map and set makes it clearer as to what is actually being stored and checked

**Comment by timstableford** [comment]
Haha maybe it's just my weird broken brain then :p By the way would you take a look at eb929a0 I had to remove some type checking to get arrays working (eg Math.min([1,2])). You *might* want to tighten it back up but keep in mind that the array elements aren't the raw type they're those objects with the type string.

**Comment by luvies** [comment]
This is full implemented now
